---
  - name: Playbook
    hosts: webservers
    become: yes
    become_user: root
    tasks:
      - name: ensure telnet is at the latest version
        ansible.builtin.apt:
          name: telnet
          state: latest
